owner: Hans5958
repo: PreMiD-upptime
user-agent: Hans5958
sites:
  - name: Main
    url: https://premid.app
  - name: Beta
    url: https://beta.premid.app
  - name: Docs
    url: https://docs.premid.app
  - name: API
    url: https://api.premid.app
status-website:
  name: PreMiD Upptime
  introTitle: "Welcome to the **PreMiD's** (unofficial) **Upptime status page**."
  introMessage: Sometimes [status.premid.app](status.premid.app) is inaccurate because there are some downtimes that are not recorded. Let's fix that.
