owner: Hans5958
repo: PreMiD-Upptime

sites:
  - name: Main
    url: https://premid.app
  - name: Beta
    url: https://beta.premid.app
  - name: Docs
    url: https://docs.premid.app
  - name: API
    url: https://api.premid.app

status-website:
  name: PreMiD Status (unofficial)
  introTitle: Welcome to **PreMiD**'s (unofficial) Upptime status page.
  introMessage: Sometimes [status.premid.app](https://status.premid.app) doesn't record downtimes. This website records downtimes for free, using only GitHub services, thanks to [Upptime](https://github.com/upptime/upptime).
  cname: premid-upptime.netlify.app
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

user-agent: Auto5958
commitMessages:
  commitAuthorName: Auto5958
  commitAuthorEmail: 69833949+Auto5958@users.noreply.github.com
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
